/* eslint-disable linebreak-style */
const users = require('./users/users.service.js');
const likes = require('./likes/likes.service.js');
const rates = require('./rates/rates.service.js');
const comments = require('./comments/comments.service.js');
const expertises = require('./expertises/expertises.service.js');
const uploads = require('./uploads/uploads.service.js');
const messages = require('./messages/messages.service.js');
const events = require('./events/events.service.js');
const userTypes = require('./userTypes/userTypes.service.js');
const eventRequests = require('./eventRequests/eventRequests.service.js');
const expertiseUser = require('./expertiseUser/expertiseUser.service.js');
const acceptFile = require('./acceptFile/acceptFile.service.js');
const files = require('./files/files.service.js');
const scores = require('./scores/scores.service.js');
const orders = require('./orders/orders.service.js');
const rateTitles = require('./rateTitles/rateTitles.service.js');
const recordTypes = require('./recordTypes/recordTypes.service.js');
const voip = require('./voip/voip.service.js');
const attempts = require('./attempts/attempts.service.js');
const services = require('./services/services.service.js');
const plans = require('./plans/plans.service.js');
const prices = require('./prices/prices.service.js');
const routes = require('./routes/routes.service.js');
const issues = require('./issues/issues.service.js');
const conversations = require('./conversations/conversations.service.js');
const subjects = require('./subjects/subjects.service.js');
const accepts = require('./accepts/accepts.service.js');
const settings = require('./settings/settings.service.js');
const questions = require('./questions/questions.service.js');
const questionCategories = require('./questionCategories/questionCategories.service.js');
const memos = require('./memos/memos.service.js');
const tickets = require('./tickets/tickets.service.js');
const departments = require('./departments/departments.service.js');
const notifications = require('./notifications/notifications.service.js');
const checkouts = require('./checkouts/checkouts.service.js');

module.exports = function (app) {
  app.configure(notifications);
  app.configure(settings);
  app.configure(accepts);
  app.configure(services);
  app.configure(users);
  app.configure(expertises);
  app.configure(uploads);
  app.configure(messages);
  app.configure(events);
  app.configure(userTypes);
  app.configure(eventRequests);
  app.configure(expertiseUser);
  app.configure(acceptFile);
  app.configure(files);
  app.configure(scores);
  app.configure(orders);
  app.configure(voip);
  app.configure(attempts);
  app.configure(likes);
  app.configure(rates);
  app.configure(memos);
  app.configure(comments);
  app.configure(plans);
  app.configure(prices);
  app.configure(routes);
  app.configure(issues);
  app.configure(conversations);
  app.configure(subjects);
  app.configure(tickets);
  app.configure(departments);
  app.configure(rateTitles);
  app.configure(recordTypes);
  app.configure(questions);
  app.configure(checkouts);
  app.configure(questionCategories);
};
